### ISSUE TITLE
Test coverage seems a bit low?

### ISSUE THREAD

**Issue by matthiasgoergens** [Plonky3/Plonky3#15]
```bash
$ cargo tarpaulin --all-features
[...]
2.65% coverage, 29/1094 lines covered, +0.00% change in coverage
```

Note, running `cargo tarpaulin` requires `cargo install tarpaulin` and the fixes from https://github.com/Plonky3/Plonky3/pull/12 because tarpaulin wants to build all targets by default, and some of them are currently broken.

**Comment by dlubarov** [comment]
Seems a bit better now -

> 28.93% coverage, 561/1939 lines covered

It's still low, and I agree we should have more tests, though there are a couple other explanations for it
- A lot of code (e.g. FRI) is just incomplete, so it's not possible to test yet.
- Since we don't really have end-to-end provers/verifiers working quite, we can't have broader integration tests, which would touch a lot of code.

Will work on increasing this but I don't think we should keep an issue open for it, since it's not really a specific task, and deciding whether we've reached the goal is somewhat subjective.
