### ISSUE TITLE
DFT base is reversed.

### ISSUE THREAD

**Issue by LKY-stephen** [Plonky3/Plonky3#171]
After some painful debugging, I found the current DFT implementation is using a different group compared to the generator provided by the group.

In NaiveDft and all other DFT implementations that are consistent with that, including Mersenne31Dft

```rust
let g = F::two_adic_generator(log_h);

let mut res = RowMajorMatrix::new(vec![F::zero(); w * h], w);
for (res_r, point) in g.powers().take(h).enumerate() {
    for (src_r, point_power) in point.powers().take(h).enumerate() {
        for c in 0..w {
            res.values[res_r * w + c] += point_power * mat.values[src_r * w + c]
        }
    }
}
```
Usually, we predict DFT is on {1,g,g^2,g^3,...}, but now it is over {1, g^-1, g^-2,g^-3,g^-4...}.  This can be a trap for users and developers (and me). Is there any specific reason to do that?

**Comment by dlubarov** [comment]
I don't quite understand, where is `-1` coming from in that code?

**Comment by LKY-stephen** [comment]
The DFT is usually `X[j] = \Sigma x[k]g^{-kj}`. For example: https://www.robinscheibler.org/2013/02/13/real-fft.html#

**Comment by dlubarov** [comment]
Hm I see what you mean, though I think we need to separate the classic DFT definition from the more general one (aka NTT). There's a clear convention for the classic DFT, but when thinking in more general terms, we can either view it as

1. `X[j] = \sum x[k] ω^{kj}`, with `ω = e^{-2 pi i / n}` chosen as our primitive `n`th root
2. `X[j] = \sum x[k] ω^{-kj}`, with `ω = e^{2 pi i / n}`

I think (1) seems more conventional, e.g. [this](https://mathworld.wolfram.com/NumberTheoreticTransform.html) and [this](https://www.nayuki.io/page/number-theoretic-transform-integer-dft) frame it that way.

**Comment by LKY-stephen** [comment]
yeah, i know it works. The only issue for me is when I implement the m31 lde logic, i need to inverse the tau. https://github.com/Plonky3/Plonky3/pull/172. In general, this is a little bit against our intuition about dft over subgroup. I feel we need to add some comments or documente it somewhere.

**Comment by LKY-stephen** [comment]
One another way to view this issue. When we are doing IDFT, we need to compute `x[j] = \frac{1}{N}\Sigma x[k]g^{-kj}` according to the above code, which means the DFT poly is evaluated on the reversed group.

**Comment by dlubarov** [comment]
Considering these transforms,

1. `\sum x[k] g^{k j}`
2. `\sum x[k] g^{-k j}`
3. `1/N \sum x[k] g^{k j}`
4. `1/N \sum x[k] g^{-k j}`

I think the modern convention seems to be to define a forward NTT as (1), and an inverse NTT as (4).

The CircleFFT paper uses the opposite convention, defining a forward DFT as (4) and an inverse DFT as (1). I think this convention stems from the continuous Fourier transform; @ulrich-haboeck might know better. Perhaps renaming DFT to NTT would help clarify that we're not using this more classic convention?

I've never encountered (2) or (3); could they be accidental hybrids of the other options?

(I'm ignoring definitions of the complex DFT when trying to determine what's conventional, since those could be generalized differently based on how we define `g`, as mentioned earlier.)

**Comment by ulrich-haboeck** [comment]
Exactly. I am considering as "forward" Fourier transform the transformation which, given the values over the group, computes the coefficients w.r.t. a specific basis, the monomial one in the case of the classical "multiplicative" FFT.
Algebraic text books often start off with the inverse problem, i.e. domain evaluation, and define that one as the Fourier transform. This is perfectly fine in the context of the classical FFT, but in my opinion less intuitive in other cases (such as the "additive" FFT) where the choice of the suitable basis is not obvious.
After all, it is just convention, and I believe that you can find all different kinds of definitions (in particular when it come to where to put the norming factor `1/N`).

**Comment by LKY-stephen** [comment]
OK, since this is as expected, we can close this issue.
