### ISSUE TITLE
Should there be `AirWithPublicValues`?

### ISSUE THREAD

**Issue by nyunyunyunyu** [Plonky3/Plonky3#466]
Simliar to `width`/`preprocessed_trace`https://github.com/Plonky3/Plonky3/blob/2335309c7f3b05cbe67d648a47120de9972e8dfa/air/src/air.rs#L8
An air should be able to tell how many public values it needs.

**Comment by dlubarov** [comment]
I think that makes sense, not sure it's strictly needed but it would at least simplify certain security matters, i.e. it's cleanest if the transcript has a fixed size/shape to rule out things like length-extension attacks (if the hash doesn't already take care of it).

Wouldn't want to make all AIRs specify it since most don't use public inputs, but I think we can just have it default to 0. Want to make the change? Or I'm happy to, either way.

**Comment by nyunyunyunyu** [comment]
> I think that makes sense, not sure it's strictly needed but it would at least simplify certain security matters, i.e. it's cleanest if the transcript has a fixed size/shape to rule out things like length-extension attacks (if the hash doesn't already take care of it).
> 
> Wouldn't want to make all AIRs specify it since most don't use public inputs, but I think we can just have it default to 0. Want to make the change? Or I'm happy to, either way.

Sure, quick PR: https://github.com/Plonky3/Plonky3/pull/470
